@baseAddress = http://localhost:5203
@categoryId = 08dcfc41-c7cd-3d55-dc4a-3eefe35b0000

GET {{baseAddress}}/api/categories
Accept: application/json

###

POST {{baseAddress}}/api/categories
Accept: application/json
Content-Type: application/json
{
  "name": "Category 1",
  "description": "Category 1 description"
}

###
GET {{baseAddress}}/api/categories/{{categoryId}}
Accept: application/json

###
POST {{baseAddress}}/api/courses
Accept: application/json
Content-Type: application/json

{
  "name": "Course 1",
  "description": "Course 1 description",
  "price": 99.99,
  "imageUrl": "http://www.example.com/image.jpg",
  "categoryId": "{{categoryId}}"
}