global using Asp.Versioning.Builder;
global using Learnify.Bus;
global using Learnify.Order.API.Endpoints.CreateOrder;
global using Learnify.Order.API.Endpoints.Orders;
global using Learnify.Order.API.Features.GetOrders;
global using Learnify.Order.Application.BackgroundServices;
global using Learnify.Order.Application.Features.Orders.Create;
global using Learnify.Order.Application.Interfaces;
global using Learnify.Order.Application.Interfaces.Refit;
global using Learnify.Order.Persistence;
global using Learnify.Order.Persistence.Repositories;
global using Learnify.Shared.Extensions;
global using Learnify.Shared.Filters;
global using MediatR;
global using Microsoft.EntityFrameworkCore;
global using ProblemDetails = Microsoft.AspNetCore.Mvc.ProblemDetails;
